version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: pg-cadastro-pessoas
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-cadastro
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    env_file: .env

  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file: .env

volumes:
  pg_data: